[package]
name = "rust-sample-app"
version = "0.1.0"
authors = ["Kostis Kapelonis <kostis@codefresh.io>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.7.3"
